name: CI

on:
  pull_request:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Format
        run: npx prettier . --write

      - name: Commit formatting
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git diff --cached --quiet || git commit -m "auto format"
          git push

      - name: Build
        run: npm run build
